/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encuesta;

import Control.controlador;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author Home
 */
public class Pregunta26 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pregunta26
     */
    double puntos;
    controlador c;
    public Pregunta26() {
        c = new controlador();
        String p = c.leer("puntos");
        puntos = Double.parseDouble(p);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("26.-¿Por qué no es bueno que una adolecente se embarace?");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Puede perder sus amigos");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Se puede quedar ciega");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Puede adquirir una ITS");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("No sé");

        jButton1.setText("RESULTADOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean sel = true;
        if(jRadioButton1.isSelected())
        puntos = puntos + 0;
        else if(jRadioButton2.isSelected())
        puntos = puntos + 0;

        else if(jRadioButton3.isSelected())
        puntos = puntos + 1.0;
        else if(jRadioButton4.isSelected())
        puntos = puntos + 0;
        //else
        //sel = false;
        if (sel) {
            c.incremento(2, puntos);
            BigDecimal bd = new BigDecimal(puntos);
            bd = bd.setScale(2, RoundingMode.HALF_UP);	// Ponemos 2 decimales
            //System.out.println(bd.doubleValue());
            System.out.println(bd);
            c.guardar("puntos", String.valueOf(bd));
            RESULTADOS abrir= new RESULTADOS();
            Principal.jDesktopPane1.add(abrir);
            abrir.show();
            this.dispose();

        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
