/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encuesta;

import Control.controlador;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author Home
 */
public class Pregunta20 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pregunta20
     */
    double puntos;
    controlador c;
    public Pregunta20() {
        c = new controlador();
        String p = c.leer("puntos");
        puntos = Double.parseDouble(p);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Falso");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("No sé");

        jButton1.setText("Siguiente Pregunta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("20.- ¿La falta de información de metodos anticonceptivos es ");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Cierto");

        jLabel2.setText("una causa para que una adolecente pueda quedar embarazada?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jRadioButton2)
                        .addComponent(jRadioButton6)
                        .addComponent(jLabel2)
                        .addComponent(jRadioButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(9, 9, 9)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean sel = true;
        if(jRadioButton1.isSelected())
        puntos = puntos + 0;
        else if(jRadioButton2.isSelected())
        puntos = puntos + 1.0;

        else if(jRadioButton6.isSelected())
        puntos = puntos + 0;
        //else
        //sel = false;
        if (sel) {

            // TODO add your handling code here:

            BigDecimal bd = new BigDecimal(puntos);
            bd = bd.setScale(2, RoundingMode.HALF_UP);	// Ponemos 2 decimales
            //System.out.println(bd.doubleValue());
            System.out.println(bd);
            c.guardar("puntos", String.valueOf(bd));
            Pregunta21 abrir= new Pregunta21();
            Principal.jDesktopPane1.add(abrir);
            abrir.show();
            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton6;
    // End of variables declaration//GEN-END:variables
}
